/**
 * Automatically translated from Python to Java
 * 
 * Original file: include/Library.py
 * Module: Library
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.converted.app.model;

class Book:
    def __init__(self, title, author):
        self.title = title
        self.author = author

    def get_title(self):
        return self.title

    def get_author(self):
        return self.author

book = Book("1984", "George Orwell")
print(book.get_title())
print(book.get_author())
public class Book {
    private String title;
    private String author;

    public Book(String title, String author) {
        this.title = title;
        this.author = author;
    }

    public String getTitle() {
        return this.title;
    }

    public String getAuthor() {
        return this.author;
    }

    public static void main(String[] args) {
        Book book = new Book("1984", "George Orwell");
        System.out.println(book.getTitle());
        System.out.println(book.getAuthor());
    }
}