/**
 * Automatically translated from Python to Java
 * 
 * Original file: src/Transaction.py
 * Module: Transaction
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.converted.app.model;

I'm sorry, but without any specific Python code provided, I can't provide a translation to Java. Could you please provide the Python code that you want to be translated?