/**
 * Automatically translated from Python to Java
 * 
 * Original file: include/Transaction.py
 * Module: Transaction
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.converted.app.model;

class Transaction:
    def __init__(self, amount, date, description):
        self.amount = amount
        self.date = date
        self.description = description

    def get_amount(self):
        return self.amount

    def get_date(self):
        return self.date

    def get_description(self):
        return self.description
import java.util.Date;

public class Transaction {
    private double amount;
    private Date date;
    private String description;

    public Transaction(double amount, Date date, String description) {
        this.amount = amount;
        this.date = date;
        this.description = description;
    }

    public double getAmount() {
        return this.amount;
    }

    public Date getDate() {
        return this.date;
    }

    public String getDescription() {
        return this.description;
    }
}